version: "3.7"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3305:3305
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 12345678

volumes:
  mariadb:
